services:
  - type: web
    name: konjabags-ai-agent
    runtime: node
    buildCommand: npm install && npm run setup && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # Manually add your existing PostgreSQL connection string
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: REDIRECT_URL
        value: https://konjabags-ai-agent.onrender.com/auth/callback
      - key: SHOPIFY_APP_URL
        value: https://konjabags-ai-agent.onrender.com